version: '3.8'

services:
  app:
    container_name: django
    restart: always
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - db
      - mcp-server
    command: >
      sh -c "python -m uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"


  mcp-server:
    container_name: mcp-server
    restart: always
    build: .
    command: >
      sh -c "chmod +x /app/run_mcp.sh && /app/run_mcp.sh"
    env_file:
      - .env
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - db

  streamlit:
    container_name: streamlit-ui
    build: .
    command: >
      sh -c "streamlit run streamlit_app.py --server.port=8501 --server.address=0.0.0.0"
    ports:
      - "8501:8501"
    env_file:
      - .env
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - app

  db:
    container_name: postgres
    restart: always
    image: postgres:15-alpine
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
